sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - DB=sqlite BRANCH=master
  - DB=postgresql BRANCH=master
  - DB=mysql BRANCH=master

addons:
  apt:
    packages:
      - python3
      - python3-jinja2
      - python3-setuptools
      - python3-pip
  postgresql: "9.3"

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

install:
  # DEBUG
  - python3 --version
  - pip --version
  # install ocdev
  - easy_install3 --user ocdev
  # set up postgresql
  - createuser -U travis -s oc_autotest
  # set up mysql
  - mysql -e 'create database oc_autotest;'
  - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost';"
  - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
  # install owncloud
  - cd ..
  - /home/travis/.local/bin/ocdev setup core --dir owncloud --branch $BRANCH --no-history
  - cd owncloud
  - ocdev ci $DB
  # enable fuel
  - mv ../fuel apps/
  - php -f console.php app:enable fuel

before_script:
  - cd apps/fuel

script:
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml
  # send coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
